### ISSUE TITLE
webiste and cdplt.scatter_gene problems

### ISSUE THREAD

**Issue by Jingle0814** [GuangyuWangLab2021/cellDancer#17]
Dear CellDancer team,
   First, The website of CellDancer (https://guangyuwanglab2021.github.io/cellDancer_website/index.html#) couldn't display completely when I logged on, so I asked the IT staff that there was a problem with the website. Can you solve it?
 
![image](https://github.com/GuangyuWangLab2021/cellDancer/assets/111042514/a2679b67-d658-41ab-935c-4d46324c58a7)
Second, following the instructions I ran into an error when I want to visual the gene velocity :
gene_list=['GATA1','KLF1','EKLF','CEBPB','ID3','EBF1','RUNX2']

ncols=5

height=math.ceil(len(gene_list)/5)*4

fig = plt.figure(figsize=(20,height))

for i in range(len(gene_list)):
    ax = fig.add_subplot(math.ceil(len(gene_list)/ncols), ncols, i+1)
    cdplt.scatter_gene(
            ax=ax,x='splice',y='unsplice',
            cellDancer_df=cellDancer_df,
            custom_xlim=None,
            custom_ylim=None,
            colors=colormap.colormap_erythroid,
            alpha=0.5,
            s = 5,
            velocity=True,
            gene=gene_list[i])
    ax.set_title(gene_list[i])
    ax.axis('off')
plt.show()
And I encountered: 
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
  File "
/miniconda3/envs/cellDancer/lib/python3.7/site-packages/celldancer/plotting/gene.py", line 126, in scatter_gene
    edgecolor="none")
  File "/miniconda3/envs/cellDancer/lib/python3.7/site-packages/matplotlib/__init__.py", line 1414, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "
/miniconda3/envs/cellDancer/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4388, in scatter
    get_next_color_func=self._get_patches_for_fill.get_next_color)
  File "
/miniconda3/envs/cellDancer/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4226, in _parse_scatter_color_args
    raise invalid_shape_exception(c.size, xsize) from err
ValueError: 'c' argument has 4895 elements, which is inconsistent with 'x' and 'y' with size 0.

**Comment by Abclisy** [comment]
hello, looks like it's displaying in the appropriate format right now. Is it displaying correctly on your side? Thank you!
