### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by chen-peng-1874** [GuangyuWangLab2021/cellDancer#3]
Hi,
I am trying to install celldancer through "pip install celldancer", however, it takes more than 1 day and not successful.
So I tried "pip install --no-deps celldancer", then install the dependencies by "pip install -r requirements.txt", but it came up with this ERROR:
```
"ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Public\miniconda3\envs\velo2\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\Public\miniconda3\envs\velo2\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\Public\miniconda3\envs\velo2\lib\site-packages\pip\_internal\commands\install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "C:\Users\Public\miniconda3\envs\velo2\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\Public\miniconda3\envs\velo2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Public\miniconda3\envs\velo2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 392, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000"
```
Where is the problem come from? Could it be due to the package version?
My Python version is 3.9.

**Comment by Abclisy** [comment]
Hi, thank you for reaching out to us. Is it possible for you to try conda and deploy the environment with python version 3.7.6? https://guangyuwanglab2021.github.io/cellDancer_website/notebooks/installation.html

Another way is to try pip install each package in requirements.txt one by one and see which one caused this problem. With more information, we will be able to target it. Now the error does not show which package caused this installation problem. We recommend trying 3.7.6 first.

If you have more questions or have an update on the problem, please feel free to comment.
