### ISSUE TITLE
Torch error

### ISSUE THREAD

**Issue by christophechu** [GuangyuWangLab2021/cellDancer#32]
I think its very hard to install celldancer. Numpy is too low to install pandas

**Comment by christophechu** [comment]
Traceback (most recent call last):   File "<stdin>", line 1, in <module>   File "/data/person/wup/public/miniconda3/envs/celldancer/lib/python3.9/site-packages/celldancer/__init__.py", line 2, in <module>     from .velocity_estimation import velocity   File "/data/person/wup/public/miniconda3/envs/celldancer/lib/python3.9/site-packages/celldancer/velocity_estimation.py", line 9, in <module>     import torch   File "/data/person/wup/public/miniconda3/envs/celldancer/lib/python3.9/site-packages/torch/__init__.py", line 197, in <module>     from torch._C import *  # noqa: F403 ImportError: /data/person/wup/public/miniconda3/envs/celldancer/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
